spring:
  datasource:
    password: 0XqFYoqbm7Rl9JSBM24YFOMLUlnilRHM
    username: chamapool_user
    # url: jdbc:postgresql://localhost:5432/chama-pool
    url: jdbc:postgresql://dpg-cjivom8cfp5c73br9aog-a.oregon-postgres.render.com/chamapool
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

africastalking:
  api-key: ${AFRICAS_TALKING_API_KEY}
  username: ${AFRICAS_TALKING_API_KEY}
  short-code: ${AFRICAS_TALKING_SHORT_CODE}
