package chamapool.domain.notifications.models;

public enum NotificationType {
  LOAN_APPLICATION,
  LOAN_APPROVAL,
  LOAN_DISBURSEMENT,
  LOAN_REPAYMENT,
  MEETING_REMINDER,
  MEETING_ATTENDANCE_CONFIRMATION,
  CONTRIBUTION_DUE,
  GENERAL_ANNOUNCEMENT
}
